### ISSUE TITLE
Can you publish the 'Den Digitale Prøvevagt' application itself ?

### ISSUE THREAD

**Issue by ghost** [vmcall/ayyxam#1]
Can you publish the 'Den Digitale Prøvevagt' application itself ?
Would like to reverse it and play around with it too.

Cheers.

And by the way: great job!

**Comment by vmcall** [comment]
The official website has now taken the executable down, but there is a mirror of the analyzed binary here: https://a.pomf.su/vNl6L.zip

**Comment by vmcall** [comment]
I'll leave this issue open for any other questions unrelated to code.
